---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes
  connection: ansible.builtin.ssh

  tasks:
  - name: Copy file
    ansible.builtin.copy:
      content: "{{ ansible_env.HOME }}" 
      dest: ~/output/path.txt

